### ISSUE TITLE
Release to rubygems.org

### ISSUE THREAD

**Issue by masutaka** [feedforce/social_plus-web_api#6]
公開しても問題ないとのことなので、以下を進めていきます。

* [x] 公開に支障のある Issue や PR がないか確認する
* [x] @sakuro の email を rubygems.org の登録メールアドレスに変更して頂く
    * https://github.com/feedforce/social_plus-web_api/blob/cac2df551400bd4a31654abe3bf9090ec0b46130/social_plus-web_api.gemspec#L10
* [x] ライセンスを決める
* [x] GitHub の public repository にする
* [ ] rubygems.org に `1.0.0` としてリリースする

**Comment by masutaka** [comment]
public repository にした。

**Comment by sakuro** [comment]
READMEのGemfileの書き方を直すのは1.0.0でやっておきますか。

**Comment by masutaka** [comment]
1.0.0 リリース前に CI を travis に変えようと思っていて、
ruby '2.2.3'
を消す予定ですか？

こちらのことでしたら、やっておきます。

**Comment by sakuro** [comment]
こいつです

```diff
-gem 'social_plus-web_api', github: 'feedforce/social_plus-web_api'
+gem 'social_plus-web_api'
```

**Comment by masutaka** [comment]
ああ、README.md ですか。やります！

**Comment by masutaka** [comment]
Released! https://rubygems.org/gems/social_plus-web_api
